/** Auto-generated by scripts/build-site-docs.mjs — do not edit manually */
import type { DocEntry } from "./types";

export const DOC_ENTRIES: DocEntry[] = [
  {
    "id": "concepts-0",
    "category": "concepts",
    "title": "JWT چیست و چه کار می‌کند؟",
    "keywords": [
      "jwt",
      "token",
      "توکن",
      "نشست",
      "session",
      "cookie",
      "احراز هویت"
    ],
    "body": "JWT مخفف JSON Web Token است — یک «کارت شناسایی دیجital» که سرور بعد از login به مرورگر می‌دهد.\n\n**چطور کار می‌کند؟**\n1. کاربر email و password را در login وارد می‌کند\n2. سرور با bcrypt رمز را چک می‌کند\n3. اگر درست بود، یک JWT می‌سازد که داخلش id، name، role کاربر است\n4. JWT داخل cookie مرورگر ذخیره می‌شود (HttpOnly)\n5. هر درخواست بعدی (fetch به API) خودکار cookie را می‌فرستد\n6. سرور JWT را decode می‌کند و می‌فهمد کی login کرده\n\n**در این پروژه:** فایل src/lib/auth.ts — NextAuth با strategy: \"jwt\"\n**مزیت:** سرور نیاز به ذخیره session در DB ندارد — همه چیز در token است\n**فیلدهای token:** id, name, email, role (USER یا ADMIN)"
  },
  {
    "id": "concepts-1",
    "category": "concepts",
    "title": "NextAuth چیست؟",
    "filePath": "src/lib/auth.ts",
    "keywords": [
      "nextauth",
      "login",
      "ورود",
      "خروج",
      "signin",
      "signout",
      "auth"
    ],
    "body": "NextAuth کتابخانه احراز هویت برای Next.js است.\n\n**فایل‌ها:**\n- src/lib/auth.ts — تنظیمات NextAuth (providers, callbacks)\n- src/app/api/auth/[...nextauth]/route.ts — API handler\n- src/components/providers/AuthProvider.tsx — wrap کل app\n\n**Credentials Provider:** login با email/password (نه Google/GitHub)\n**authorize():** کاربر را از DB پیدا می‌کند، bcrypt.compare رمز، blocked چک\n**callbacks.jwt:** اطلاعات user را در token ذخیره می‌کند\n**callbacks.session:** token را به session.user تبدیل می‌کند\n**requireAuth():** در API — اگر login نبود throw UNAUTHORIZED → 401\n**requireAdmin():** اگر role !== ADMIN → 403\n\n**استفاده در کامپوننت:** useSession() از next-auth/react\n**استفاده در server:** auth() از @/lib/auth"
  },
  {
    "id": "concepts-2",
    "category": "concepts",
    "title": "bcrypt و هش رمز عبور",
    "keywords": [
      "bcrypt",
      "password",
      "رمز",
      "hash",
      "هش",
      "امنیت"
    ],
    "body": "رمز عبور هرگز plain text در DB ذخیره نمی‌شود!\n\n**bcrypt:** الگوریتم one-way hash — از رمز نمی‌توان رمز اصلی را فهمید\n**ثبت‌نام:** bcrypt.hash(password, 10) → passwordHash در User\n**ورود:** bcrypt.compare(password, user.passwordHash) → true/false\n**فایل‌ها:** register/route.ts, auth.ts, profile/route.ts\n\n**چرا مهم است؟** اگر DB لو برود، مهاجم رمز واقعی را نمی‌بیند."
  },
  {
    "id": "concepts-3",
    "category": "concepts",
    "title": "Prisma ORM — ارتباط با دیتابیس",
    "filePath": "src/lib/prisma.ts",
    "keywords": [
      "prisma",
      "orm",
      "database",
      "دیتابیس",
      "query",
      "مدل"
    ],
    "body": "Prisma ORM لایه بین کد TypeScript و PostgreSQL است.\n\n**فایل schema:** prisma/schema.prisma — تعریف جداول (models)\n**generate:** prisma generate → client در src/generated/prisma\n**استفاده:** import { prisma } from \"@/lib/prisma\"\n**مثال:** prisma.user.findMany(), prisma.content.create({ data: {...} })\n\n**prisma.ts:** singleton client + retry روی connection error\n**seed:** prisma/seed.ts — npm run db:seed — داده اولیه admin و کتاب‌ها\n\n**چرا ORM؟** به جای SQL خام، TypeScript type-safe queries"
  },
  {
    "id": "concepts-4",
    "category": "concepts",
    "title": "PostgreSQL — دیتابیس کجاست؟",
    "filePath": "prisma/schema.prisma",
    "keywords": [
      "postgresql",
      "postgres",
      "neon",
      "database",
      "sql",
      "جدول"
    ],
    "body": "PostgreSQL دیتابیس رابطه‌ای است — همه داده‌ها در جداول (tables).\n\n**کجا host می‌شود؟** Neon PostgreSQL (cloud) — connection string در env: DATABASE_URL\n**۹ مدل اصلی:** User, Content, Category, Review, SavedContent, Notification, Ticket, TicketMessage, PasswordResetToken\n**۵ enum:** Role, ContentType, ContentStatus, NotificationType, TicketStatus\n\n**فایل schema:** prisma/schema.prisma — منبع حقیقت ساختار DB\n**migrate:** prisma migrate dev — اعمال تغییر schema\n**فقط APPROVED contents** در browse عمومی دیده می‌شوند"
  },
  {
    "id": "concepts-5",
    "category": "concepts",
    "title": "API و REST — ارتباط Frontend و Backend",
    "keywords": [
      "api",
      "rest",
      "fetch",
      "endpoint",
      "http",
      "get",
      "post"
    ],
    "body": "API راه ارتباط مرورگر با سرور است. هر API یک URL در src/app/api/\n\n**متدها:**\n- GET — خواندن (لیست کتاب‌ها)\n- POST — ایجاد (ثبت‌نام، آپلود)\n- PATCH — ویرایش جزئی (تأیید محتوا)\n- DELETE — حذف (نظر)\n\n**پاسخ:** JSON مثل { contents: [...], total: 50 }\n**خطاها:** 401=login لازم، 403=admin لازم، 404=یافت نشد، 400=ورودی بد\n\n**۳۶ route** در src/app/api/ — بخش API در راهنما همه را توضیح می‌دهد"
  },
  {
    "id": "concepts-6",
    "category": "concepts",
    "title": "React — Client vs Server Component",
    "keywords": [
      "react",
      "component",
      "client",
      "server",
      "use client",
      "state"
    ],
    "body": "React = کتابخانه UI. هر .tsx یک کامپوننت است.\n\n**Server Component (پیش‌فرض):** روی سرور render — fetch مستقیم DB — page.tsx\n**Client Component (\"use client\"):** در مرورگر — state، onClick، useEffect — BrowseSearch\n\n**۵۱ کامپوننت** در src/components/ — ui, layout, home, content, dashboard, admin, media\n\n**Props:** داده از parent به child\n**Hooks:** useState, useEffect, useSession — فقط client"
  },
  {
    "id": "concepts-7",
    "category": "concepts",
    "title": "Next.js App Router — صفحات و routing",
    "filePath": "src/app/layout.tsx",
    "keywords": [
      "nextjs",
      "next",
      "app router",
      "routing",
      "صفحه",
      "layout"
    ],
    "body": "Next.js 16 فریم‌ورک React با routing فایل‌محور.\n\n**src/app/** = صفحات\n- page.tsx = یک route (مثلاً /browse)\n- layout.tsx = wrapper مشترک (Navbar, Footer)\n- [id] = dynamic param\n\n**۱۳ صفحه:** /, /browse, /dashboard, /admin, /upload, /auth/*, /content/[id]/read|listen\n\n**API Routes:** src/app/api/**/route.ts — export GET, POST, ...\n\n**SSR:** server component داده را قبل از HTML fetch می‌کند"
  },
  {
    "id": "concepts-8",
    "category": "concepts",
    "title": "Zod — اعتبارسنجی ورودی",
    "filePath": "src/lib/validators.ts",
    "keywords": [
      "zod",
      "validation",
      "schema",
      "اعتبارسنجی"
    ],
    "body": "Zod کتابخانه validation — قبل از ذخیره در DB ورودی چک می‌شود.\n\n**فایل:** src/lib/validators.ts\n**registerSchema:** name min 2, email, password min 6\n**loginSchema, reviewSchema, searchSchema, profileUpdateSchema, ...**\n\n**استفاده:** schema.safeParse(body) → success یا error با پیام فارسی\n**چرا؟** جلوگیری از داده بد — SQL injection کمتر، UX بهتر"
  },
  {
    "id": "concepts-9",
    "category": "concepts",
    "title": "fetch — فراخوانی API از مرورگر",
    "keywords": [
      "fetch",
      "ajax",
      "request",
      "درخواست",
      "json"
    ],
    "body": "fetch() API مرورگر برای HTTP request.\n\n**GET:** fetch('/api/contents?q=حافظ').then(r => r.json())\n**POST JSON:** method POST, headers Content-Type application/json, body JSON.stringify\n**POST FormData:** برای آپلود فایل — body: formData بدون Content-Type\n\n**Cookie session:** با credentials: 'include' (پیش‌فرض same-origin) خودکار فرستاده می‌شود\n**کامپوننت‌های fetch:** BrowseSearch, SaveButton, ReviewForm, ProfileForm, TicketPanel, admin"
  },
  {
    "id": "concepts-10",
    "category": "concepts",
    "title": "Tailwind CSS — استایل",
    "filePath": "src/app/globals.css",
    "keywords": [
      "tailwind",
      "css",
      "style",
      "کلاس",
      "رنگ"
    ],
    "body": "Tailwind = utility classes در JSX — className=\"text-teal-brand px-4\"\n\n**globals.css:** theme colors — teal-brand, gold-brand, surface, muted\n**Dark mode:** next-themes + class dark:\n**RTL:** dir=\"rtl\" در html\n**cn():** src/lib/utils.ts — ترکیب کلاس‌ها"
  },
  {
    "id": "concepts-11",
    "category": "concepts",
    "title": "Storage — ذخیره فایل PDF و صوت",
    "filePath": "src/lib/storage.ts",
    "keywords": [
      "storage",
      "s3",
      "upload",
      "file",
      "فایل",
      "pdf"
    ],
    "body": "فایل‌های آپلود در S3 (production) یا disk محلی (dev) ذخیره می‌شوند.\n\n**uploadFile():** buffer → key مثل uploads/userId/uuid.pdf\n**getFileUrl():** URL برای نمایش — /api/files/... یا S3 presigned\n**archive:** fileKey با prefix ext: → embed از archive.org via /api/proxy\n\n**API:** POST /api/upload, GET /api/files/[...key], GET /api/proxy"
  },
  {
    "id": "concepts-12",
    "category": "concepts",
    "title": "TypeScript — تایپ‌های امن",
    "keywords": [
      "typescript",
      "type",
      "interface",
      "تایپ"
    ],
    "body": "TypeScript = JavaScript + types — خطا قبل از runtime.\n\n**.tsx** = React + TS, **.ts** = pure logic\n**Prisma types:** از generated client\n**Props types:** در هر کامپوننت"
  },
  {
    "id": "database-13",
    "category": "database",
    "title": "مدل User — کاربران",
    "filePath": "prisma/schema.prisma",
    "keywords": [
      "user",
      "کاربر",
      "email",
      "role",
      "admin",
      "blocked"
    ],
    "body": "جدول User — همه کاربران سایت\n\n**فیلدها:**\n- id (cuid) — شناسه یکتا\n- name — نام نمایشی\n- email (unique) — ایمیل login\n- passwordHash — رمز هش‌شده (هرگز plain)\n- role — USER یا ADMIN\n- blocked — true = login ممنوع\n- createdAt, updatedAt\n\n**روابط:** contents, reviews, saved, notifications, tickets\n**seed admin:** admin@marketplace.local / admin123"
  },
  {
    "id": "database-14",
    "category": "database",
    "title": "مدل Content — کتاب و پادکست",
    "keywords": [
      "content",
      "ebook",
      "audiobook",
      "محتوا",
      "کتاب",
      "pending",
      "approved"
    ],
    "body": "جدول Content — هر PDF یا فایل صوتی\n\n**فیلدها:** title, description, type (EBOOK|AUDIOBOOK), status (PENDING|APPROVED|REJECTED)\n**fileKey** — مسیر فایل در storage\n**coverKey** — تصویر جلد (optional)\n**authorId** → User, **categoryId** → Category\n**downloadCount** — تعداد بازدید read/listen\n\n**گردش کار:** upload → PENDING → admin approve → APPROVED → در browse"
  },
  {
    "id": "database-15",
    "category": "database",
    "title": "مدل Category — دسته‌بندی",
    "keywords": [
      "category",
      "دسته",
      "slug"
    ],
    "body": "name, slug (unique), description — مثلاً «ادبیات» slug: adabiat\n**API:** GET /api/categories"
  },
  {
    "id": "database-16",
    "category": "database",
    "title": "مدل Review — نظرات",
    "keywords": [
      "review",
      "نظر",
      "rating",
      "ستاره"
    ],
    "body": "rating 1-5, comment, status (مثل ContentStatus)\n**unique:** یک نظر per user per content\n**POST** /api/contents/[id]/reviews → PENDING تا admin تأیید"
  },
  {
    "id": "database-17",
    "category": "database",
    "title": "مدل SavedContent — کتابخانه شخصی",
    "keywords": [
      "saved",
      "bookmark",
      "ذخیره",
      "کتابخانه"
    ],
    "body": "userId + contentId — bookmark\n**API:** /api/user/saved, SaveButton.tsx"
  },
  {
    "id": "database-18",
    "category": "database",
    "title": "مدل Notification — اعلان",
    "keywords": [
      "notification",
      "اعلان",
      "notify"
    ],
    "body": "type: CONTENT_APPROVED, CONTENT_REJECTED, REVIEW_*, TICKET_REPLY\n**read:** boolean — NotificationList, badge در Navbar"
  },
  {
    "id": "database-19",
    "category": "database",
    "title": "مدل Ticket و TicketMessage — پشتیبانی",
    "keywords": [
      "ticket",
      "تیکت",
      "پشتیبانی",
      "support"
    ],
    "body": "Ticket: subject, status OPEN|ANSWERED|CLOSED\nTicketMessage: body, isStaff (پاسخ admin)\n**User API:** /api/user/tickets — **Admin:** /api/admin/tickets"
  },
  {
    "id": "database-20",
    "category": "database",
    "title": "مدل PasswordResetToken",
    "keywords": [
      "reset",
      "token",
      "بازیابی رمز"
    ],
    "body": "tokenHash, expiresAt (۱ ساعت) — forgot-password flow"
  },
  {
    "id": "api--api-register",
    "category": "api",
    "title": "POST /api/register",
    "filePath": "src/app/api/api/register/route.ts",
    "keywords": [
      "register",
      "ثبت نام",
      "/api/register",
      "POST",
      "api"
    ],
    "body": "ثبت‌نام\n\n**دسترسی:** عمومی\n\nPOST JSON: name, email, password → user ایجاد → 201. فایل: src/app/api/register/route.ts. صفحه: auth/register"
  },
  {
    "id": "api--api-auth-...nextauth",
    "category": "api",
    "title": "GET/POST /api/auth/[...nextauth]",
    "filePath": "src/app/api/api/auth/[...nextauth]/route.ts",
    "keywords": [
      "nextauth",
      "login",
      "ورود",
      "/api/auth/[...nextauth]",
      "GET/POST",
      "api"
    ],
    "body": "NextAuth — ورود و session\n\n**دسترسی:** عمومی\n\nsignIn credentials → JWT cookie. src/lib/auth.ts. login/page.tsx"
  },
  {
    "id": "api--api-auth-forgot-password",
    "category": "api",
    "title": "POST /api/auth/forgot-password",
    "filePath": "src/app/api/api/auth/forgot-password/route.ts",
    "keywords": [
      "forgot",
      "فراموشی",
      "/api/auth/forgot-password",
      "POST",
      "api"
    ],
    "body": "فراموشی رمز\n\n**دسترسی:** عمومی\n\nPOST { email } → token + email. forgot-password/page.tsx"
  },
  {
    "id": "api--api-auth-reset-password",
    "category": "api",
    "title": "POST /api/auth/reset-password",
    "filePath": "src/app/api/api/auth/reset-password/route.ts",
    "keywords": [
      "reset",
      "بازیابی",
      "/api/auth/reset-password",
      "POST",
      "api"
    ],
    "body": "بازیابی رمز\n\n**دسترسی:** عمومی\n\nPOST { token, password }. reset-password/page.tsx"
  },
  {
    "id": "api--api-contents",
    "category": "api",
    "title": "GET /api/contents",
    "filePath": "src/app/api/api/contents/route.ts",
    "keywords": [
      "contents",
      "browse",
      "جستجو",
      "list",
      "/api/contents",
      "GET",
      "api"
    ],
    "body": "لیست و جستجوی محتوا\n\n**دسترسی:** عمومی\n\nQuery: q, type, category, sort, page, pageSize. فقط APPROVED. BrowseSearch.tsx → fetch. پاسخ: contents[], total, totalPages"
  },
  {
    "id": "api--api-contents-id",
    "category": "api",
    "title": "GET /api/contents/[id]",
    "filePath": "src/app/api/api/contents/[id]/route.ts",
    "keywords": [
      "content",
      "detail",
      "جزئیات",
      "/api/contents/[id]",
      "GET",
      "api"
    ],
    "body": "جزئیات یک محتوا\n\n**دسترسی:** عمومی\n\nPath id. content + reviews. read/listen pages (server-side lib/content)"
  },
  {
    "id": "api--api-contents-id-reviews",
    "category": "api",
    "title": "POST /api/contents/[id]/reviews",
    "filePath": "src/app/api/api/contents/[id]/reviews/route.ts",
    "keywords": [
      "review",
      "نظر",
      "rating",
      "/api/contents/[id]/reviews",
      "POST",
      "api"
    ],
    "body": "ثبت نظر\n\n**دسترسی:** login\n\nPOST { rating 1-5, comment? }. ReviewForm.tsx. status PENDING"
  },
  {
    "id": "api--api-contents-id-reviews-reviewId",
    "category": "api",
    "title": "DELETE /api/contents/[id]/reviews/[reviewId]",
    "filePath": "src/app/api/api/contents/[id]/reviews/[reviewId]/route.ts",
    "keywords": [
      "delete",
      "review",
      "/api/contents/[id]/reviews/[reviewId]",
      "DELETE",
      "api"
    ],
    "body": "حذف نظر\n\n**دسترسی:** login\n\nصاحب یا admin. ReviewList.tsx"
  },
  {
    "id": "api--api-categories",
    "category": "api",
    "title": "GET /api/categories",
    "filePath": "src/app/api/api/categories/route.ts",
    "keywords": [
      "category",
      "دسته",
      "/api/categories",
      "GET",
      "api"
    ],
    "body": "لیست دسته‌ها\n\n**دسترسی:** عمومی\n\ncategories[]. upload/page, browse filter"
  },
  {
    "id": "api--api-recommendations",
    "category": "api",
    "title": "GET /api/recommendations",
    "filePath": "src/app/api/api/recommendations/route.ts",
    "keywords": [
      "recommend",
      "پیشنهاد",
      "/api/recommendations",
      "GET",
      "api"
    ],
    "body": "پیشنهاد هوشمند\n\n**دسترسی:** عمومی\n\nmax 6. logged-in: based on reviews. home page.tsx"
  },
  {
    "id": "api--api-upload",
    "category": "api",
    "title": "POST /api/upload",
    "filePath": "src/app/api/api/upload/route.ts",
    "keywords": [
      "upload",
      "آپلود",
      "pdf",
      "/api/upload",
      "POST",
      "api"
    ],
    "body": "آپلود PDF/صوت\n\n**دسترسی:** login\n\nFormData: title, type, categoryId, file. status PENDING. upload/page.tsx → storage.ts"
  },
  {
    "id": "api--api-files-...key",
    "category": "api",
    "title": "GET /api/files/[...key]",
    "filePath": "src/app/api/api/files/[...key]/route.ts",
    "keywords": [
      "files",
      "download",
      "pdf",
      "/api/files/[...key]",
      "GET",
      "api"
    ],
    "body": "سرو فایل\n\n**دسترسی:** عمومی\n\nStream PDF/audio. PdfViewer, AudioPlayer"
  },
  {
    "id": "api--api-proxy",
    "category": "api",
    "title": "GET /api/proxy",
    "filePath": "src/app/api/api/proxy/route.ts",
    "keywords": [
      "proxy",
      "archive",
      "/api/proxy",
      "GET",
      "api"
    ],
    "body": "پروکسی archive.org\n\n**دسترسی:** عمومی\n\n?url= archive.org only. CORS bypass"
  },
  {
    "id": "api--api-user-profile",
    "category": "api",
    "title": "GET/PATCH /api/user/profile",
    "filePath": "src/app/api/api/user/profile/route.ts",
    "keywords": [
      "profile",
      "پروفایل",
      "/api/user/profile",
      "GET/PATCH",
      "api"
    ],
    "body": "پروفایل کاربر\n\n**دسترسی:** login\n\nGET: user+stats. PATCH: name یا password. ProfileForm, dashboard"
  },
  {
    "id": "api--api-user-saved",
    "category": "api",
    "title": "GET/POST /api/user/saved",
    "filePath": "src/app/api/api/user/saved/route.ts",
    "keywords": [
      "saved",
      "bookmark",
      "/api/user/saved",
      "GET/POST",
      "api"
    ],
    "body": "کتابخانه — لیست و افزودن\n\n**دسترسی:** login\n\nPOST { contentId }. SaveButton, dashboard"
  },
  {
    "id": "api--api-user-saved-contentId",
    "category": "api",
    "title": "GET/DELETE /api/user/saved/[contentId]",
    "filePath": "src/app/api/api/user/saved/[contentId]/route.ts",
    "keywords": [
      "saved",
      "/api/user/saved/[contentId]",
      "GET/DELETE",
      "api"
    ],
    "body": "وضعیت bookmark\n\n**دسترسی:** login\n\nGET saved:true/false. DELETE unbookmark. SaveButton"
  },
  {
    "id": "api--api-user-uploads",
    "category": "api",
    "title": "GET /api/user/uploads",
    "filePath": "src/app/api/api/user/uploads/route.ts",
    "keywords": [
      "uploads",
      "آپلود",
      "/api/user/uploads",
      "GET",
      "api"
    ],
    "body": "آپلودهای من\n\n**دسترسی:** login\n\nهمه status. dashboard tab uploads"
  },
  {
    "id": "api--api-user-notifications",
    "category": "api",
    "title": "GET/PATCH /api/user/notifications",
    "filePath": "src/app/api/api/user/notifications/route.ts",
    "keywords": [
      "notification",
      "اعلان",
      "/api/user/notifications",
      "GET/PATCH",
      "api"
    ],
    "body": "اعلان‌ها\n\n**دسترسی:** login\n\nGET 50 + unreadCount. PATCH mark all read. NotificationList"
  },
  {
    "id": "api--api-user-notifications-id-read",
    "category": "api",
    "title": "PATCH /api/user/notifications/[id]/read",
    "filePath": "src/app/api/api/user/notifications/[id]/read/route.ts",
    "keywords": [
      "notification",
      "/api/user/notifications/[id]/read",
      "PATCH",
      "api"
    ],
    "body": "خواندن یک اعلان\n\n**دسترسی:** login\n\nPATCH. NotificationList"
  },
  {
    "id": "api--api-user-tickets",
    "category": "api",
    "title": "GET/POST /api/user/tickets",
    "filePath": "src/app/api/api/user/tickets/route.ts",
    "keywords": [
      "ticket",
      "تیکت",
      "/api/user/tickets",
      "GET/POST",
      "api"
    ],
    "body": "تیکت پشتیبانی\n\n**دسترسی:** login\n\nPOST subject+body. TicketPanel"
  },
  {
    "id": "api--api-user-tickets-id",
    "category": "api",
    "title": "GET/POST /api/user/tickets/[id]",
    "filePath": "src/app/api/api/user/tickets/[id]/route.ts",
    "keywords": [
      "ticket",
      "/api/user/tickets/[id]",
      "GET/POST",
      "api"
    ],
    "body": "مکالمه تیکت\n\n**دسترسی:** login\n\nGET messages. POST reply. TicketPanel"
  },
  {
    "id": "api--api-admin-stats",
    "category": "api",
    "title": "GET /api/admin/stats",
    "filePath": "src/app/api/api/admin/stats/route.ts",
    "keywords": [
      "stats",
      "آمار",
      "admin",
      "/api/admin/stats",
      "GET",
      "api"
    ],
    "body": "آمار KPI\n\n**دسترسی:** admin\n\nusers, contents, reviews stats. AdminStats.tsx"
  },
  {
    "id": "api--api-admin-pending",
    "category": "api",
    "title": "GET /api/admin/pending",
    "filePath": "src/app/api/api/admin/pending/route.ts",
    "keywords": [
      "pending",
      "تأیید",
      "moderation",
      "/api/admin/pending",
      "GET",
      "api"
    ],
    "body": "صف تأیید\n\n**دسترسی:** admin\n\ncontents + reviews PENDING. admin/page pending tab"
  },
  {
    "id": "api--api-admin-contents-id-approve",
    "category": "api",
    "title": "PATCH /api/admin/contents/[id]/approve",
    "filePath": "src/app/api/api/admin/contents/[id]/approve/route.ts",
    "keywords": [
      "approve",
      "تأیید",
      "/api/admin/contents/[id]/approve",
      "PATCH",
      "api"
    ],
    "body": "تأیید محتوا\n\n**دسترسی:** admin\n\nAPPROVED + notification. admin page"
  },
  {
    "id": "api--api-admin-contents-id-reject",
    "category": "api",
    "title": "PATCH /api/admin/contents/[id]/reject",
    "filePath": "src/app/api/api/admin/contents/[id]/reject/route.ts",
    "keywords": [
      "reject",
      "رد",
      "/api/admin/contents/[id]/reject",
      "PATCH",
      "api"
    ],
    "body": "رد محتوا\n\n**دسترسی:** admin\n\nREJECTED + notification"
  },
  {
    "id": "api--api-admin-reviews-id-approve",
    "category": "api",
    "title": "PATCH /api/admin/reviews/[id]/approve",
    "filePath": "src/app/api/api/admin/reviews/[id]/approve/route.ts",
    "keywords": [
      "review",
      "approve",
      "/api/admin/reviews/[id]/approve",
      "PATCH",
      "api"
    ],
    "body": "تأیید نظر\n\n**دسترسی:** admin\n\nundefined"
  },
  {
    "id": "api--api-admin-reviews-id-reject",
    "category": "api",
    "title": "PATCH /api/admin/reviews/[id]/reject",
    "filePath": "src/app/api/api/admin/reviews/[id]/reject/route.ts",
    "keywords": [
      "review",
      "reject",
      "/api/admin/reviews/[id]/reject",
      "PATCH",
      "api"
    ],
    "body": "رد نظر\n\n**دسترسی:** admin\n\nundefined"
  },
  {
    "id": "api--api-admin-users",
    "category": "api",
    "title": "GET /api/admin/users",
    "filePath": "src/app/api/api/admin/users/route.ts",
    "keywords": [
      "users",
      "کاربران",
      "/api/admin/users",
      "GET",
      "api"
    ],
    "body": "لیست کاربران\n\n**دسترسی:** admin\n\n?page&q. AdminUserList"
  },
  {
    "id": "api--api-admin-users-id",
    "category": "api",
    "title": "PATCH /api/admin/users/[id]",
    "filePath": "src/app/api/api/admin/users/[id]/route.ts",
    "keywords": [
      "user",
      "block",
      "/api/admin/users/[id]",
      "PATCH",
      "api"
    ],
    "body": "ویرایش کاربر\n\n**دسترسی:** admin\n\nrole, blocked, password. AdminUserList"
  },
  {
    "id": "api--api-admin-users-id-reset-password",
    "category": "api",
    "title": "POST /api/admin/users/[id]/reset-password",
    "filePath": "src/app/api/api/admin/users/[id]/reset-password/route.ts",
    "keywords": [
      "password",
      "reset",
      "/api/admin/users/[id]/reset-password",
      "POST",
      "api"
    ],
    "body": "ریست رمز توسط admin\n\n**دسترسی:** admin\n\nundefined"
  },
  {
    "id": "api--api-admin-top-users",
    "category": "api",
    "title": "GET /api/admin/top-users",
    "filePath": "src/app/api/api/admin/top-users/route.ts",
    "keywords": [
      "top",
      "leaderboard",
      "/api/admin/top-users",
      "GET",
      "api"
    ],
    "body": "Leaderboard\n\n**دسترسی:** admin\n\n?category=uploads|reviews|saved|downloads. AdminTopUsers"
  },
  {
    "id": "api--api-admin-tickets",
    "category": "api",
    "title": "GET /api/admin/tickets",
    "filePath": "src/app/api/api/admin/tickets/route.ts",
    "keywords": [
      "ticket",
      "admin",
      "/api/admin/tickets",
      "GET",
      "api"
    ],
    "body": "همه تیکت‌ها\n\n**دسترسی:** admin\n\n?status. AdminTickets"
  },
  {
    "id": "api--api-admin-tickets-id",
    "category": "api",
    "title": "GET/PATCH/POST /api/admin/tickets/[id]",
    "filePath": "src/app/api/api/admin/tickets/[id]/route.ts",
    "keywords": [
      "ticket",
      "/api/admin/tickets/[id]",
      "GET/PATCH/POST",
      "api"
    ],
    "body": "مدیریت تیکت\n\n**دسترسی:** admin\n\nreply staff, change status. AdminTickets"
  },
  {
    "id": "api--api-admin-import-archive",
    "category": "api",
    "title": "POST /api/admin/import-archive",
    "filePath": "src/app/api/api/admin/import-archive/route.ts",
    "keywords": [
      "import",
      "archive",
      "/api/admin/import-archive",
      "POST",
      "api"
    ],
    "body": "واردات archive.org\n\n**دسترسی:** admin\n\n~100 کتاب. admin import button"
  },
  {
    "id": "api--api-admin-contents",
    "category": "api",
    "title": "GET /api/admin/contents",
    "filePath": "src/app/api/api/admin/contents/route.ts",
    "keywords": [
      "admin",
      "contents",
      "/api/admin/contents",
      "GET",
      "api"
    ],
    "body": "لیست PENDING contents\n\n**دسترسی:** admin\n\nundefined"
  },
  {
    "id": "api--api-admin-reviews",
    "category": "api",
    "title": "GET /api/admin/reviews",
    "filePath": "src/app/api/api/admin/reviews/route.ts",
    "keywords": [
      "admin",
      "reviews",
      "/api/admin/reviews",
      "GET",
      "api"
    ],
    "body": "لیست PENDING reviews\n\n**دسترسی:** admin\n\nundefined"
  },
  {
    "id": "flows-57",
    "category": "flows",
    "title": "جریان ثبت‌نام و ورود",
    "keywords": [
      "flow",
      "login",
      "register"
    ],
    "body": "1. POST /api/register 2. redirect login 3. signIn → JWT 4. session در cookie"
  },
  {
    "id": "flows-58",
    "category": "flows",
    "title": "جریان مرور و مطالعه کتاب",
    "keywords": [
      "browse",
      "read",
      "pdf"
    ],
    "body": "GET /api/contents → ContentCard → /content/[id]/read → PdfViewer → /api/files یا /api/proxy"
  },
  {
    "id": "flows-59",
    "category": "flows",
    "title": "جریان آپلود و تأیید",
    "keywords": [
      "upload",
      "approve"
    ],
    "body": "GET categories → POST upload PENDING → admin pending → PATCH approve → notification"
  },
  {
    "id": "flows-60",
    "category": "flows",
    "title": "جریان نظرات",
    "keywords": [
      "review"
    ],
    "body": "POST review PENDING → admin approve → نمایش در ReviewList"
  },
  {
    "id": "flows-61",
    "category": "flows",
    "title": "جریان تیکت پشتیبانی",
    "keywords": [
      "ticket"
    ],
    "body": "User POST ticket → Admin GET tickets → POST reply → TICKET_REPLY notify"
  },
  {
    "id": "flows-62",
    "category": "flows",
    "title": "نقشه پوشه‌های پروژه",
    "keywords": [
      "structure",
      "ساختار",
      "پوشه"
    ],
    "body": "src/components/ — 51 UI\nsrc/lib/ — 16 logic\nsrc/app/ — pages + api\nprisma/ — DB schema\npublic/ — PWA"
  },
  {
    "id": "file-src-components-ui-Button-tsx",
    "category": "frontend",
    "title": "Button",
    "filePath": "src/components/ui/Button.tsx",
    "keywords": [
      "Button",
      "src/components/ui/Button.tsx",
      "ui Button.tsx"
    ],
    "body": "**هدف:** دکمه استاندارد با variant و اندازه‌های مختلف.\n\n- variantها: primary, secondary, ghost, danger, accent, hero\n- اندازه‌ها: sm, md, lg با حداقل ارتفاع لمسی\n- `forwardRef` برای دسترسی به DOM\n\n**خروجی‌ها:** `Button`\n\n**استفاده‌شده در:** تقریباً همه فرم‌ها و پنل‌ها (auth, dashboard, admin, upload, layout, content, media)"
  },
  {
    "id": "file-src-components-ui-Card-tsx",
    "category": "frontend",
    "title": "Card",
    "filePath": "src/components/ui/Card.tsx",
    "keywords": [
      "Card",
      "src/components/ui/Card.tsx",
      "ui Card.tsx"
    ],
    "body": "**هدف:** کانتینر پنل با پس‌زمینه و گوشه گرد.\n\n- کلاس `surface-panel` با padding پیش‌فرض\n- `forwardRef` برای ref به div\n\n**خروجی‌ها:** `Card`\n\n**استفاده‌شده در:** dashboard, admin, auth, upload, content pages, NotificationList, TicketPanel"
  },
  {
    "id": "file-src-components-ui-Input-tsx",
    "category": "frontend",
    "title": "Input",
    "filePath": "src/components/ui/Input.tsx",
    "keywords": [
      "Input",
      "src/components/ui/Input.tsx",
      "ui Input.tsx"
    ],
    "body": "**هدف:** فیلد ورودی متنی استایل‌دار.\n\n- border و focus ring teal-brand\n- `forwardRef` برای فرم‌ها\n\n**خروجی‌ها:** `Input`\n\n**استفاده‌شده در:** auth pages, ProfileForm, AdminUserList, TicketPanel, upload, PasswordInput"
  },
  {
    "id": "file-src-components-ui-PasswordInput-tsx",
    "category": "frontend",
    "title": "PasswordInput",
    "filePath": "src/components/ui/PasswordInput.tsx",
    "keywords": [
      "PasswordInput",
      "src/components/ui/PasswordInput.tsx",
      "ui PasswordInput.tsx"
    ],
    "body": "**هدف:** ورودی رمز با دکمه نمایش/مخفی‌سازی.\n\n- state داخلی visible\n- آیکون Eye/EyeOff از lucide\n- wrapper روی `Input`\n\n**خروجی‌ها:** `PasswordInput`\n\n**استفاده‌شده در:** login, register, reset-password, ProfileForm, AdminUserList"
  },
  {
    "id": "file-src-components-ui-Pagination-tsx",
    "category": "frontend",
    "title": "Pagination",
    "filePath": "src/components/ui/Pagination.tsx",
    "keywords": [
      "Pagination",
      "src/components/ui/Pagination.tsx",
      "ui Pagination.tsx"
    ],
    "body": "**هدف:** صفحه‌بندی RTL با دکمه قبل/بعد و نقطه‌ها.\n\n- نمایش شماره صفحه به فارسی\n- `PageSizeSelect` برای تعداد در صفحه\n- مخفی شدن اگر فقط یک صفحه باشد\n\n**خروجی‌ها:** `Pagination`, `PageSizeSelect`\n\n**استفاده‌شده در:** `BrowseSearch`, `PaginatedContentGrid`, `AdminUserList`, `AdminTickets`, `AdminTopUsers`"
  },
  {
    "id": "file-src-components-ui-PersianLoader-tsx",
    "category": "frontend",
    "title": "PersianLoader",
    "filePath": "src/components/ui/PersianLoader.tsx",
    "keywords": [
      "PersianLoader",
      "src/components/ui/PersianLoader.tsx",
      "ui PersianLoader.tsx"
    ],
    "body": "**هدف:** لودر تم‌دار فارسی با انیمیشن orbit.\n\n- نمایش label قابل تنظیم\n- نام سایت از `SITE_NAME`\n- SVG الماس/طلایی\n\n**خروجی‌ها:** `PersianLoader`\n\n**استفاده‌شده در:** `loading.tsx` (root, browse, dashboard), login, reset-password, browse, dashboard, admin, TicketPanel, AdminTickets, BrowseSearch"
  },
  {
    "id": "file-src-components-ui-ScrollReveal-tsx",
    "category": "frontend",
    "title": "ScrollReveal",
    "filePath": "src/components/ui/ScrollReveal.tsx",
    "keywords": [
      "ScrollReveal",
      "src/components/ui/ScrollReveal.tsx",
      "ui ScrollReveal.tsx"
    ],
    "body": "**هدف:** انیمیشن ظاهر شدن هنگام scroll با IntersectionObserver.\n\n- variantها: up, left, right, scale, fade, blur, rise\n- delay و once قابل تنظیم\n- client component\n\n**خروجی‌ها:** `ScrollReveal`\n\n**استفاده‌شده در:** `page.tsx`, `browse/page.tsx`, `HomeSections`, `TopicSlider`, `BrowseSearch`"
  },
  {
    "id": "file-src-components-ui-Textarea-tsx",
    "category": "frontend",
    "title": "Textarea",
    "filePath": "src/components/ui/Textarea.tsx",
    "keywords": [
      "Textarea",
      "src/components/ui/Textarea.tsx",
      "ui Textarea.tsx"
    ],
    "body": "**هدف:** textarea چندخطی با استایل یکسان Input.\n\n- حداقل ارتفاع 28\n- focus ring teal\n\n**خروجی‌ها:** `Textarea`\n\n**استفاده‌شده در:** `ReviewForm`, `upload/page.tsx`"
  },
  {
    "id": "file-src-components-layout-SiteLogo-tsx",
    "category": "frontend",
    "title": "SiteLogo",
    "filePath": "src/components/layout/SiteLogo.tsx",
    "keywords": [
      "SiteLogo",
      "src/components/layout/SiteLogo.tsx",
      "layout SiteLogo.tsx"
    ],
    "body": "**هدف:** نمایش لوگوی سایت با Next/Image.\n\n- اندازه قابل تنظیم (پیش‌فرض 56)\n- از `SITE_LOGO` و `SITE_NAME`\n\n**خروجی‌ها:** `SiteLogo`\n\n**استفاده‌شده در:** `Navbar`, `Footer`, `DownloadClient`"
  },
  {
    "id": "file-src-components-layout-ThemeToggle-tsx",
    "category": "frontend",
    "title": "ThemeToggle",
    "filePath": "src/components/layout/ThemeToggle.tsx",
    "keywords": [
      "ThemeToggle",
      "src/components/layout/ThemeToggle.tsx",
      "layout ThemeToggle.tsx"
    ],
    "body": "**هدف:** دکمه تعویض تم روشن/تاریک.\n\n- از `next-themes` استفاده می‌کند\n- placeholder تا mount برای جلوگیری از hydration mismatch\n\n**خروجی‌ها:** `ThemeToggle`\n\n**استفاده‌شده در:** `Navbar`"
  },
  {
    "id": "file-src-components-layout-AppShellScript-tsx",
    "category": "frontend",
    "title": "AppShellScript",
    "filePath": "src/components/layout/AppShellScript.tsx",
    "keywords": [
      "AppShellScript",
      "src/components/layout/AppShellScript.tsx",
      "layout AppShellScript.tsx"
    ],
    "body": "**هدف:** اسکript inline برای تشخیص PWA/Capacitor.\n\n- ست کردن `data-app-shell=\"true\"` روی html\n- تشخیص standalone و Capacitor native\n\n**خروجی‌ها:** `AppShellScript`\n\n**استفاده‌شده در:** `src/app/layout.tsx` (در `<head>`)"
  },
  {
    "id": "file-src-components-layout-MobileBottomNav-tsx",
    "category": "frontend",
    "title": "MobileBottomNav",
    "filePath": "src/components/layout/MobileBottomNav.tsx",
    "keywords": [
      "MobileBottomNav",
      "src/components/layout/MobileBottomNav.tsx",
      "layout MobileBottomNav.tsx"
    ],
    "body": "**هدف:** ناوبری پایین موبایل با ۵ آیتم.\n\n- آیتم‌ها: حساب، پشتیبانی/مدیریت، خانه (مرکز), کتاب, آپلود\n- مخفی در auth/read/listen\n- نقش ADMIN را از session می‌خواند\n\n**خروجی‌ها:** `MobileBottomNav`\n\n**استفاده‌شده در:** `MobileBottomNavShell`"
  },
  {
    "id": "file-src-components-layout-MobileBottomNavShell-tsx",
    "category": "frontend",
    "title": "MobileBottomNavShell",
    "filePath": "src/components/layout/MobileBottomNavShell.tsx",
    "keywords": [
      "MobileBottomNavShell",
      "src/components/layout/MobileBottomNavShell.tsx",
      "layout MobileBottomNavShell.tsx"
    ],
    "body": "**هدف:** wrapper با Suspense برای MobileBottomNav.\n\n- fallback null\n- لازم برای useSearchParams\n\n**خروجی‌ها:** `MobileBottomNavShell`\n\n**استفاده‌شده در:** `src/app/layout.tsx`"
  },
  {
    "id": "file-src-components-layout-PageEntrance-tsx",
    "category": "frontend",
    "title": "PageEntrance",
    "filePath": "src/components/layout/PageEntrance.tsx",
    "keywords": [
      "PageEntrance",
      "src/components/layout/PageEntrance.tsx",
      "layout PageEntrance.tsx"
    ],
    "body": "**هدف:** انیمیشن ورود صفحه با کلاس CSS.\n\n- wrapper ساده با `page-enter page-enter-active`\n\n**خروجی‌ها:** `PageEntrance`\n\n**استفاده‌شده در:** `src/app/layout.tsx` (دور children در main)"
  },
  {
    "id": "file-src-components-layout-PwaRegister-tsx",
    "category": "frontend",
    "title": "PwaRegister",
    "filePath": "src/components/layout/PwaRegister.tsx",
    "keywords": [
      "PwaRegister",
      "src/components/layout/PwaRegister.tsx",
      "layout PwaRegister.tsx"
    ],
    "body": "**هدف:** ثبت service worker برای PWA.\n\n- register `/sw.js` در useEffect\n- خطا را silent می‌گیرد\n\n**خروجی‌ها:** `PwaRegister`\n\n**استفاده‌شده در:** `src/app/layout.tsx`"
  },
  {
    "id": "file-src-components-layout-Navbar-tsx",
    "category": "frontend",
    "title": "Navbar",
    "filePath": "src/components/layout/Navbar.tsx",
    "keywords": [
      "Navbar",
      "src/components/layout/Navbar.tsx",
      "layout Navbar.tsx"
    ],
    "body": "**هدف:** هدر اصلی سایت با لینک‌ها و auth.\n\n- لینک‌های خانه، browse، upload، دانلود اپ (در وب)\n- ThemeToggle، ورود/ثبت‌نام یا UserAccountButton\n- لینک admin برای نقش ADMIN\n- از `useAppShellMode` برای مخفی کردن لینک دانلود در اپ\n\n**خروجی‌ها:** `Navbar`\n\n**استفاده‌شده در:** `src/app/layout.tsx`"
  },
  {
    "id": "file-src-components-layout-BackToTop-tsx",
    "category": "frontend",
    "title": "BackToTop",
    "filePath": "src/components/layout/BackToTop.tsx",
    "keywords": [
      "BackToTop",
      "src/components/layout/BackToTop.tsx",
      "layout BackToTop.tsx"
    ],
    "body": "**هدف:** دکمه شناور برگشت به بالای صفحه.\n\n- نمایش بعد از 120px scroll\n- موقعیت بالای bottom nav در موبایل\n- smooth scroll\n\n**خروجی‌ها:** `BackToTop`\n\n**استفاده‌شده در:** `src/app/layout.tsx`"
  },
  {
    "id": "file-src-components-layout-UserAccountButton-tsx",
    "category": "frontend",
    "title": "UserAccountButton",
    "filePath": "src/components/layout/UserAccountButton.tsx",
    "keywords": [
      "UserAccountButton",
      "src/components/layout/UserAccountButton.tsx",
      "layout UserAccountButton.tsx"
    ],
    "body": "**هدف:** دکمه حساب کاربری و badge نوتیف در navbar.\n\n- لینک به dashboard\n- badge تعداد unread از `useNotifications`\n- فقط برای session\n\n**خروجی‌ها:** `UserAccountButton`\n\n**استفاده‌شده در:** `Navbar`"
  },
  {
    "id": "file-src-components-layout-Footer-tsx",
    "category": "frontend",
    "title": "Footer",
    "filePath": "src/components/layout/Footer.tsx",
    "keywords": [
      "Footer",
      "src/components/layout/Footer.tsx",
      "layout Footer.tsx"
    ],
    "body": "**هدف:** فوتر دسکتاپ با لوگو و شعار.\n\n- فقط md:block (مخفی در موبایل)\n- نام و شعار سایت\n\n**خروجی‌ها:** `Footer`\n\n**استفاده‌شده در:** `src/app/layout.tsx`"
  },
  {
    "id": "file-src-components-home-HomeSections-tsx",
    "category": "frontend",
    "title": "HomeSections",
    "filePath": "src/components/home/HomeSections.tsx",
    "keywords": [
      "HomeSections",
      "src/components/home/HomeSections.tsx",
      "home HomeSections.tsx"
    ],
    "body": "**هدف:** سه بخش محتوا در صفحه اصلی.\n\n- تاریخ ایران و جهان (فیلتر category/title)\n- پیشنهاد برای شما\n- جدیدترین‌ها با لینک «مشاهده همه»\n- هر بخش حداکثر ۴ کارت\n\n**خروجی‌ها:** `HomeSections`\n\n**استفاده‌شده در:** `src/app/page.tsx`"
  },
  {
    "id": "file-src-components-home-TopicSlider-tsx",
    "category": "frontend",
    "title": "TopicSlider",
    "filePath": "src/components/home/TopicSlider.tsx",
    "keywords": [
      "TopicSlider",
      "src/components/home/TopicSlider.tsx",
      "home TopicSlider.tsx"
    ],
    "body": "**هدف:** اسلایدر افقی موضوعات با autoplay و loop بی‌نهایت.\n\n- کپی ۳ برابری slides برای loop\n- pause روی hover/touch\n- لینک به browse با query params\n- آیکون بر اساس نوع موضوع\n\n**خروجی‌ها:** `TopicSlider`\n\n**استفاده‌شده در:** `src/app/page.tsx`"
  },
  {
    "id": "file-src-components-content-ContentGrid-tsx",
    "category": "frontend",
    "title": "ContentGrid",
    "filePath": "src/components/content/ContentGrid.tsx",
    "keywords": [
      "ContentGrid",
      "src/components/content/ContentGrid.tsx",
      "content ContentGrid.tsx"
    ],
    "body": "**هدف:** grid ساده از ContentCard بدون صفحه‌بندی.\n\n- grid responsive 2 تا 5 ستون\n- پیام خالی قابل تنظیم\n\n**خروجی‌ها:** `ContentGrid`\n\n**استفاده‌شده در:** `UserLists` (SavedList)"
  },
  {
    "id": "file-src-components-content-PaginatedContentGrid-tsx",
    "category": "frontend",
    "title": "PaginatedContentGrid",
    "filePath": "src/components/content/PaginatedContentGrid.tsx",
    "keywords": [
      "PaginatedContentGrid",
      "src/components/content/PaginatedContentGrid.tsx",
      "content PaginatedContentGrid.tsx"
    ],
    "body": "**هدف:** grid محتوا با صفحه‌بندی client-side.\n\n- slice آرایه items\n- reset page هنگام تغییر items\n- columns: home یا browse\n\n**خروجی‌ها:** `PaginatedContentGrid`\n\n**استفاده‌شده در:** *(فعلاً import نشده)*"
  },
  {
    "id": "file-src-components-content-BrowseSearch-tsx",
    "category": "frontend",
    "title": "BrowseSearch",
    "filePath": "src/components/content/BrowseSearch.tsx",
    "keywords": [
      "BrowseSearch",
      "src/components/content/BrowseSearch.tsx",
      "content BrowseSearch.tsx"
    ],
    "body": "**هدف:** UI جستجو و فیلتر browse با fetch از API.\n\n- debounce 300ms و sync URL\n- فیلتر: q, type, category, sort, pageSize\n- fetch `/api/contents`\n- ScrollReveal روی هر کارت\n\n**خروجی‌ها:** `BrowseSearch`\n\n**استفاده‌شده در:** `src/app/browse/page.tsx`"
  },
  {
    "id": "file-src-components-content-SaveButton-tsx",
    "category": "frontend",
    "title": "SaveButton",
    "filePath": "src/components/content/SaveButton.tsx",
    "keywords": [
      "SaveButton",
      "src/components/content/SaveButton.tsx",
      "content SaveButton.tsx"
    ],
    "body": "**هدف:** دکمه ذخیره/حذف از کتابخانه.\n\n- فقط برای authenticated\n- GET/POST/DELETE `/api/user/saved`\n- state saved و loading\n\n**خروجی‌ها:** `SaveButton`\n\n**استفاده‌شده در:** `read/page.tsx`, `listen/page.tsx`"
  },
  {
    "id": "file-src-components-content-StarRating-tsx",
    "category": "frontend",
    "title": "StarRating",
    "filePath": "src/components/content/StarRating.tsx",
    "keywords": [
      "StarRating",
      "src/components/content/StarRating.tsx",
      "content StarRating.tsx"
    ],
    "body": "**هدف:** نمایش ۵ ستاره با امتیاز عددی.\n\n- round value برای پر شدن ستاره‌ها\n- showValue اختیاری\n\n**خروجی‌ها:** `StarRating`\n\n**استفاده‌شده در:** `ContentCard`, `ReviewList`, read/listen pages, `admin/page.tsx`"
  },
  {
    "id": "file-src-components-content-ReviewList-tsx",
    "category": "frontend",
    "title": "ReviewList",
    "filePath": "src/components/content/ReviewList.tsx",
    "keywords": [
      "ReviewList",
      "src/components/content/ReviewList.tsx",
      "content ReviewList.tsx"
    ],
    "body": "**هدف:** لیست نظرات با امکان حذف.\n\n- حذف توسط صاحب نظر یا admin\n- confirm و router.refresh\n- StarRating برای هر نظر\n\n**خروجی‌ها:** `ReviewList`\n\n**استفاده‌شده در:** `read/page.tsx`, `listen/page.tsx`"
  },
  {
    "id": "file-src-components-content-ReviewForm-tsx",
    "category": "frontend",
    "title": "ReviewForm",
    "filePath": "src/components/content/ReviewForm.tsx",
    "keywords": [
      "ReviewForm",
      "src/components/content/ReviewForm.tsx",
      "content ReviewForm.tsx"
    ],
    "body": "**هدف:** فرم ثبت نظر با امتیاز ۱–۵.\n\n- POST `/api/contents/[id]/reviews`\n- پیام تأیید مدیر\n- Textarea برای comment\n\n**خروجی‌ها:** `ReviewForm`\n\n**استفاده‌شده در:** `read/page.tsx`, `listen/page.tsx`"
  },
  {
    "id": "file-src-components-dashboard-ProfileForm-tsx",
    "category": "frontend",
    "title": "ProfileForm",
    "filePath": "src/components/dashboard/ProfileForm.tsx",
    "keywords": [
      "ProfileForm",
      "src/components/dashboard/ProfileForm.tsx",
      "dashboard ProfileForm.tsx"
    ],
    "body": "**هدف:** ویرایش نام، رمز و خروج از حساب.\n\n- PATCH `/api/user/profile`\n- update session با next-auth\n- بخش جداگانه signOut\n\n**خروجی‌ها:** `ProfileForm`\n\n**استفاده‌شده در:** `src/app/dashboard/page.tsx`"
  },
  {
    "id": "file-src-components-dashboard-NotificationList-tsx",
    "category": "frontend",
    "title": "NotificationList",
    "filePath": "src/components/dashboard/NotificationList.tsx",
    "keywords": [
      "NotificationList",
      "src/components/dashboard/NotificationList.tsx",
      "dashboard NotificationList.tsx"
    ],
    "body": "**هدف:** لیست نوتیف‌ها و hook مدیریت آن‌ها.\n\n- انواع CONTENT/REVIEW approved/rejected\n- mark read / mark all read\n- poll هر ۶۰ ثانیه\n- لینک embed شده در message\n\n**خروجی‌ها:** `NotificationList`, `NotificationItem` (type), `useNotifications`\n\n**استفاده‌شده در:** `dashboard/page.tsx`, `UserAccountButton`"
  },
  {
    "id": "file-src-components-dashboard-TicketPanel-tsx",
    "category": "frontend",
    "title": "TicketPanel",
    "filePath": "src/components/dashboard/TicketPanel.tsx",
    "keywords": [
      "TicketPanel",
      "src/components/dashboard/TicketPanel.tsx",
      "dashboard TicketPanel.tsx"
    ],
    "body": "**هدف:** پنل تیکت پشتیبانی کاربر.\n\n- ایجاد تیکت جدید\n- لیست و جزئیات گفتگو\n- reply تا وضعیت CLOSED\n- API `/api/user/tickets`\n\n**خروجی‌ها:** `TicketPanel`\n\n**استفاده‌شده در:** `src/app/dashboard/page.tsx`"
  },
  {
    "id": "file-src-components-admin-AnimateOnView-tsx",
    "category": "frontend",
    "title": "AnimateOnView",
    "filePath": "src/components/admin/AnimateOnView.tsx",
    "keywords": [
      "AnimateOnView",
      "src/components/admin/AnimateOnView.tsx",
      "admin AnimateOnView.tsx"
    ],
    "body": "**هدف:** wrapper declarative برای انیمیشن scroll.\n\n- prop `as` برای tag دلخواه\n- callback `onVisibleChange`\n\n**خروجی‌ها:** `AnimateOnView`\n\n**استفاده‌شده در:** AdminStats, AdminUserList, AdminTopUsers, `admin/page.tsx`"
  },
  {
    "id": "file-src-components-admin-AnimatedNumber-tsx",
    "category": "frontend",
    "title": "AnimatedNumber",
    "filePath": "src/components/admin/AnimatedNumber.tsx",
    "keywords": [
      "AnimatedNumber",
      "src/components/admin/AnimatedNumber.tsx",
      "admin AnimatedNumber.tsx"
    ],
    "body": "**هدف:** شمارنده انیمیشن‌دار با easing.\n\n- فرمت fa-IR\n- reset به ۰ هنگام active\n\n**خروجی‌ها:** `AnimatedNumber`\n\n**استفاده‌شده در:** HomeHero, AdminStats, AdminBarChart, AdminDonutChart, AdminStatsHero, AdminTopUsers, AdminUserList"
  },
  {
    "id": "file-src-components-admin-AdminBarChart-tsx",
    "category": "frontend",
    "title": "AdminBarChart",
    "filePath": "src/components/admin/AdminBarChart.tsx",
    "keywords": [
      "AdminBarChart",
      "src/components/admin/AdminBarChart.tsx",
      "admin AdminBarChart.tsx"
    ],
    "body": "**هدف:** نمودار میله‌ای افقی با انیمیشن.\n\n- BarRow با AnimatedNumber\n- درصد نسبت به max\n\n**خروجی‌ها:** `AdminBarChart`, `BarItem` (type)\n\n**استفاده‌شده در:** `AdminStats`"
  },
  {
    "id": "file-src-components-admin-AdminDonutChart-tsx",
    "category": "frontend",
    "title": "AdminDonutChart",
    "filePath": "src/components/admin/AdminDonutChart.tsx",
    "keywords": [
      "AdminDonutChart",
      "src/components/admin/AdminDonutChart.tsx",
      "admin AdminDonutChart.tsx"
    ],
    "body": "**هدف:** نمودار دونات SVG با legend.\n\n- stroke-dasharray انیمیشن\n- centerLabel/centerValue\n- LegendItem با درصد\n\n**خروجی‌ها:** `AdminDonutChart`, `DonutSegment` (type)\n\n**استفاده‌شده در:** `AdminStats`"
  },
  {
    "id": "file-src-components-admin-AdminStatsHero-tsx",
    "category": "frontend",
    "title": "AdminStatsHero",
    "filePath": "src/components/admin/AdminStatsHero.tsx",
    "keywords": [
      "AdminStatsHero",
      "src/components/admin/AdminStatsHero.tsx",
      "admin AdminStatsHero.tsx"
    ],
    "body": "**هدف:** hero بنر آمار در بالای داشبورد admin.\n\n- pillهای کاربر فعال، محتوای تأییدشده، دسته‌ها\n- پس‌زمینه گرادیان و orb\n\n**خروجی‌ها:** `AdminStatsHero`\n\n**استفاده‌شده در:** `AdminStats`"
  },
  {
    "id": "file-src-components-admin-AdminStats-tsx",
    "category": "frontend",
    "title": "AdminStats",
    "filePath": "src/components/admin/AdminStats.tsx",
    "keywords": [
      "AdminStats",
      "src/components/admin/AdminStats.tsx",
      "admin AdminStats.tsx"
    ],
    "body": "**هدف:** داشبورد آمار کامل سایت.\n\n- fetch `/api/admin/stats`\n- KPI cards، donut charts، bar charts، mini stats\n- skeleton loading\n\n**خروجی‌ها:** `AdminStats`\n\n**استفاده‌شده در:** `src/app/admin/page.tsx`"
  },
  {
    "id": "file-src-components-admin-AdminUserList-tsx",
    "category": "frontend",
    "title": "AdminUserList",
    "filePath": "src/components/admin/AdminUserList.tsx",
    "keywords": [
      "AdminUserList",
      "src/components/admin/AdminUserList.tsx",
      "admin AdminUserList.tsx"
    ],
    "body": "**هدف:** مدیریت کاربران با جستجو و pagination.\n\n- تغییر role، block/unblock، reset password\n- جدول desktop + کارت mobile\n- modal تغییر رمز\n\n**خروجی‌ها:** `AdminUserList`\n\n**استفاده‌شده در:** `src/app/admin/page.tsx`"
  },
  {
    "id": "file-src-components-admin-AdminTopUsers-tsx",
    "category": "frontend",
    "title": "AdminTopUsers",
    "filePath": "src/components/admin/AdminTopUsers.tsx",
    "keywords": [
      "AdminTopUsers",
      "src/components/admin/AdminTopUsers.tsx",
      "admin AdminTopUsers.tsx"
    ],
    "body": "**هدف:** رتبه‌بندی کاربران برتر.\n\n- دسته‌ها: uploads, reviews, saved, downloads\n- podium top 3\n- progress bar نسبی\n\n**خروجی‌ها:** `AdminTopUsers`\n\n**استفاده‌شده در:** `src/app/admin/page.tsx`"
  },
  {
    "id": "file-src-components-admin-AdminTickets-tsx",
    "category": "frontend",
    "title": "AdminTickets",
    "filePath": "src/components/admin/AdminTickets.tsx",
    "keywords": [
      "AdminTickets",
      "src/components/admin/AdminTickets.tsx",
      "admin AdminTickets.tsx"
    ],
    "body": "**هدف:** مدیریت تیکت‌های پشتیبانی توسط admin.\n\n- فیلتر وضعیت OPEN/ANSWERED/CLOSED\n- پاسخ staff و بستن/بازگشایی\n- pagination\n\n**خروجی‌ها:** `AdminTickets`\n\n**استفاده‌شده در:** `src/app/admin/page.tsx`"
  },
  {
    "id": "file-src-components-admin-AdminTabPanel-tsx",
    "category": "frontend",
    "title": "AdminTabPanel",
    "filePath": "src/components/admin/AdminTabPanel.tsx",
    "keywords": [
      "AdminTabPanel",
      "src/components/admin/AdminTabPanel.tsx",
      "admin AdminTabPanel.tsx"
    ],
    "body": "**هدف:** wrapper ساده برای tab panels admin.\n\n- key برای re-mount\n- کلاس `admin-tab-panel`\n\n**خروجی‌ها:** `AdminTabPanel`\n\n**استفاده‌شده در:** `src/app/admin/page.tsx`"
  },
  {
    "id": "file-src-components-media-AudioPlayer-tsx",
    "category": "frontend",
    "title": "AudioPlayer",
    "filePath": "src/components/media/AudioPlayer.tsx",
    "keywords": [
      "AudioPlayer",
      "src/components/media/AudioPlayer.tsx",
      "media AudioPlayer.tsx"
    ],
    "body": "**هدف:** پخش‌کننده صوتی HTML5 یا embed archive.\n\n- play/pause، seek bar، duration\n- fallback iframe برای archive\n- خطای «غیرقابل پخش»\n\n**خروجی‌ها:** `AudioPlayer`\n\n**استفاده‌شده در:** `src/app/content/[id]/listen/page.tsx`"
  },
  {
    "id": "file-src-components-providers-ThemeProvider-tsx",
    "category": "frontend",
    "title": "ThemeProvider",
    "filePath": "src/components/providers/ThemeProvider.tsx",
    "keywords": [
      "ThemeProvider",
      "src/components/providers/ThemeProvider.tsx",
      "providers ThemeProvider.tsx"
    ],
    "body": "**هدف:** wrapper next-themes.\n\n- attribute class، defaultTheme light\n- enableSystem، disableTransitionOnChange\n\n**خروجی‌ها:** `ThemeProvider`\n\n**استفاده‌شده در:** `src/app/layout.tsx`"
  },
  {
    "id": "file-src-lib-button-styles-ts",
    "category": "backend",
    "title": "button-styles",
    "filePath": "src/lib/button-styles.ts",
    "keywords": [
      "button-styles",
      "src/lib/button-styles.ts",
      "lib button-styles.ts"
    ],
    "body": "**هدف:** کلاس‌های CSS مشترک دکمه.\n\n- `buttonInteraction`: hover scale/shadow\n- `buttonNavClass`: استایل nav pagination\n\n**خروجی‌ها:** `buttonInteraction`, `buttonNavClass`\n\n**استفاده‌شده در:** `Button`, `Pagination`, `BackToTop`"
  },
  {
    "id": "file-src-lib-site-ts",
    "category": "backend",
    "title": "site",
    "filePath": "src/lib/site.ts",
    "keywords": [
      "site",
      "src/lib/site.ts",
      "lib site.ts"
    ],
    "body": "**هدف:** ثابت‌های برند و URL سایت.\n\n- SITE_NAME, SITE_SLOGAN, SITE_LOGO, SITE_URL\n- ANDROID_APK_URL, IOS_INSTALL_URL, PWA_INSTALL_URL\n\n**خروجی‌ها:** ثابت‌های بالا\n\n**استفاده‌شده در:** layout, Navbar, Footer, PersianLoader, SiteLogo, email, download"
  },
  {
    "id": "file-src-lib-app-shell-ts",
    "category": "backend",
    "title": "app-shell",
    "filePath": "src/lib/app-shell.ts",
    "keywords": [
      "app-shell",
      "src/lib/app-shell.ts",
      "lib app-shell.ts"
    ],
    "body": "**هدف:** تشخیص حالت اپ (PWA/Capacitor).\n\n- `isStandaloneDisplay`, `isNativeCapacitorApp`, `isAppShellMode`\n\n**خروجی‌ها:** توابع بالا\n\n**استفاده‌شده در:** `useAppShellMode`, `AppShellScript` (منطق مشابه inline)"
  },
  {
    "id": "file-src-lib-prisma-ts",
    "category": "backend",
    "title": "prisma",
    "filePath": "src/lib/prisma.ts",
    "keywords": [
      "prisma",
      "src/lib/prisma.ts",
      "lib prisma.ts"
    ],
    "body": "**هدف:** singleton PrismaClient با adapter PostgreSQL.\n\n- Proxy برای lazy init و stale client detection\n- `withPrismaRetry` با reconnect\n- `isPrismaConnectionError`\n\n**خروجی‌ها:** `prisma`, `withPrismaRetry`, `isPrismaConnectionError`\n\n**استفاده‌شده در:** همه API routes، content.ts, auth.ts, notifications, users, password-reset, archive-import, pages"
  },
  {
    "id": "file-src-lib-auth-ts",
    "category": "backend",
    "title": "auth",
    "filePath": "src/lib/auth.ts",
    "keywords": [
      "auth",
      "src/lib/auth.ts",
      "lib auth.ts"
    ],
    "body": "**هدف:** پیکربندی NextAuth v5 با Credentials.\n\n- JWT session با role در token\n- `requireAuth`, `requireAdmin`\n- export handlers, signIn, signOut, auth\n\n**خروجی‌ها:** `handlers`, `signIn`, `signOut`, `auth`, `requireAuth`, `requireAdmin`\n\n**استفاده‌شده در:** API routes، pages (home, read, listen)، `[...nextauth]/route.ts`"
  },
  {
    "id": "file-src-lib-validators-ts",
    "category": "backend",
    "title": "validators",
    "filePath": "src/lib/validators.ts",
    "keywords": [
      "validators",
      "src/lib/validators.ts",
      "lib validators.ts"
    ],
    "body": "**هدف:** schemaهای Zod برای validation API.\n\n- register, login, forgot/reset password\n- contentUpload, review, search, profile\n- ticket schemas\n\n**خروجی‌ها:** schemaهای Zod\n\n**استفاده‌شده در:** API routes (register, auth, upload, reviews, contents, profile, tickets)"
  },
  {
    "id": "file-src-lib-email-utils-ts",
    "category": "backend",
    "title": "email-utils",
    "filePath": "src/lib/email-utils.ts",
    "keywords": [
      "email-utils",
      "src/lib/email-utils.ts",
      "lib email-utils.ts"
    ],
    "body": "**هدف:** نرمال‌سازی ایمیل.\n\n- trim + lowercase\n\n**خروجی‌ها:** `normalizeEmail`\n\n**استفاده‌شده در:** auth.ts, users.ts, register, forgot-password"
  },
  {
    "id": "file-src-lib-users-ts",
    "category": "backend",
    "title": "users",
    "filePath": "src/lib/users.ts",
    "keywords": [
      "users",
      "src/lib/users.ts",
      "lib users.ts"
    ],
    "body": "**هدف:** جستجوی کاربر بر اساس ایمیل.\n\n- case-insensitive با Prisma\n\n**خروجی‌ها:** `findUserByEmail`, `findUserIdByEmail`\n\n**استفاده‌شده در:** *(احتمالاً API routes — grep مستقیم محدود)*"
  },
  {
    "id": "file-src-lib-email-ts",
    "category": "backend",
    "title": "email",
    "filePath": "src/lib/email.ts",
    "keywords": [
      "email",
      "src/lib/email.ts",
      "lib email.ts"
    ],
    "body": "**هدف:** ارسال ایمیل بازیابی رمز با nodemailer.\n\n- `smtpConfigured`, `sendPasswordResetEmail`\n- HTML RTL فارسی\n- fallback log در dev بدون SMTP\n\n**خروجی‌ها:** `smtpConfigured`, `sendPasswordResetEmail`\n\n**استفاده‌شده در:** `api/auth/forgot-password/route.ts`"
  },
  {
    "id": "file-src-lib-password-reset-ts",
    "category": "backend",
    "title": "password-reset",
    "filePath": "src/lib/password-reset.ts",
    "keywords": [
      "password-reset",
      "src/lib/password-reset.ts",
      "lib password-reset.ts"
    ],
    "body": "**هدف:** مدیریت token بازیابی رمز.\n\n- hash SHA256، TTL ۱ ساعت\n- create/clear/resetWithToken\n- `buildResetPasswordUrl`, `getAppBaseUrl`\n\n**خروجی‌ها:** توابع token و URL\n\n**استفاده‌شده در:** forgot-password API, reset-password API, profile API, admin user routes"
  },
  {
    "id": "file-src-lib-content-ts",
    "category": "backend",
    "title": "content",
    "filePath": "src/lib/content.ts",
    "keywords": [
      "content",
      "src/lib/content.ts",
      "lib content.ts"
    ],
    "body": "**هدف:** لایه داده محتوا (query + map).\n\n- `getApprovedContents` با sort/filter/pagination\n- `getRecommendations` بر اساس تاریخچه review\n- `getContentById` با reviews\n- `mapContent`, `contentInclude`\n\n**خروجی‌ها:** توابع و typeهای MappedContent, PaginatedContents\n\n**استفاده‌شده در:** pages (home, browse, read, listen)، API contents/saved/uploads/recommendations"
  },
  {
    "id": "file-src-lib-storage-ts",
    "category": "backend",
    "title": "storage",
    "filePath": "src/lib/storage.ts",
    "keywords": [
      "storage",
      "src/lib/storage.ts",
      "lib storage.ts"
    ],
    "body": "**هدف:** آپلود و URL فایل (S3 یا local).\n\n- `uploadFile`, `getFileUrl`, `buildFileKey`\n- پشتیبانی archive: و ext: keys\n- signed URL S3 یا `/api/files/`\n\n**خروجی‌ها:** توابع storage\n\n**استفاده‌شده در:** upload API, read/listen pages, files API, seed, archive-import"
  },
  {
    "id": "file-src-lib-notifications-ts",
    "category": "backend",
    "title": "notifications",
    "filePath": "src/lib/notifications.ts",
    "keywords": [
      "notifications",
      "src/lib/notifications.ts",
      "lib notifications.ts"
    ],
    "body": "**هدف:** ایجاد و enrich نوتیف‌ها.\n\n- notify content/review approved/rejected\n- `enrichNotification` با contentLink\n- `getContentHref`\n\n**خروجی‌ها:** توابع notification\n\n**استفاده‌شده در:** admin approve/reject routes، user notifications API"
  },
  {
    "id": "file-src-lib-topic-slides-ts",
    "category": "backend",
    "title": "topic-slides",
    "filePath": "src/lib/topic-slides.ts",
    "keywords": [
      "topic-slides",
      "src/lib/topic-slides.ts",
      "lib topic-slides.ts"
    ],
    "body": "**هدف:** ساخت داده اسلایder موضوعات صفحه اصلی.\n\n- `TopicSlide` type\n- `buildTopicSlides` از categories + type counts\n- تصاویر از `/public/slides`\n\n**خروجی‌ها:** `TopicSlide` (type), `buildTopicSlides`\n\n**استفاده‌شده در:** `page.tsx`, `TopicSlider`"
  },
  {
    "id": "file-src-lib-archive-import-ts",
    "category": "backend",
    "title": "archive-import",
    "filePath": "src/lib/archive-import.ts",
    "keywords": [
      "archive-import",
      "src/lib/archive-import.ts",
      "lib archive-import.ts"
    ],
    "body": "**هدف:** واردات انبوه از Internet Archive.\n\n- merge VERIFIED_ARCHIVE + ARCHIVE_CATALOG\n- upsert categories، create authors\n- tryOnlineImport از API archive.org\n\n**خروجی‌ها:** `runArchiveImport`, `buildMergedCatalog`, `ArchiveCatalogEntry`, `ArchiveImportResult`\n\n**استفاده‌شده در:** `prisma/import-archive.ts`, `api/admin/import-archive/route.ts`"
  },
  {
    "id": "file-src-app-browse-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/browse/page.tsx",
    "keywords": [
      "page",
      "src/app/browse/page.tsx",
      "browse page.tsx"
    ],
    "body": "**هدف:** صفحه مرور و جستجوی محتوا.\n\n- SSR initial data + BrowseSearch client\n- Suspense + PersianLoader\n\n**خروجی‌ها:** `BrowsePage`\n\n**استفاده از:** BrowseSearch, getApprovedContents, prisma.category"
  },
  {
    "id": "file-src-app-dashboard-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/dashboard/page.tsx",
    "keywords": [
      "page",
      "src/app/dashboard/page.tsx",
      "dashboard page.tsx"
    ],
    "body": "**هدف:** پنل کاربری با ۶ tab.\n\n- overview, saved, uploads, notifications, tickets, profile\n- guard unauthenticated → login\n- fetch profile/saved/uploads APIs\n\n**خروجی‌ها:** `DashboardPage`\n\n**استفاده از:** NotificationList, ProfileForm, TicketPanel, UserLists, useNotifications"
  },
  {
    "id": "file-src-app-admin-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/admin/page.tsx",
    "keywords": [
      "page",
      "src/app/admin/page.tsx",
      "admin page.tsx"
    ],
    "body": "**هدف:** پنل مدیر با ۵ tab.\n\n- pending (content/review approve), stats, users, tickets, top users\n- import archive button\n- guard ADMIN role\n\n**خروجی‌ها:** `AdminPage`\n\n**استفاده از:** AdminStats, AdminUserList, AdminTopUsers, AdminTickets, AdminTabPanel"
  },
  {
    "id": "file-src-app-upload-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/upload/page.tsx",
    "keywords": [
      "page",
      "src/app/upload/page.tsx",
      "upload page.tsx"
    ],
    "body": "**هدف:** فرم آپلود PDF/صوتی.\n\n- require login\n- FormData POST `/api/upload`\n- fetch categories\n\n**خروجی‌ها:** `UploadPage`"
  },
  {
    "id": "file-src-app-download-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/download/page.tsx",
    "keywords": [
      "page",
      "src/app/download/page.tsx",
      "download page.tsx"
    ],
    "body": "**هدف:** صفحه دانلود اپ (SSR metadata).\n\n- pass props به DownloadClient\n- metadata SEO\n\n**خروجی‌ها:** `DownloadPage`\n\n**استفاده از:** `lib/site`, `DownloadClient.tsx`"
  },
  {
    "id": "file-src-app-logo-preview-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/logo-preview/page.tsx",
    "keywords": [
      "page",
      "src/app/logo-preview/page.tsx",
      "logo-preview page.tsx"
    ],
    "body": "**هدف:** پیش‌نمایش ۴ گزینه لوگو (A–D).\n\n- grid با پس‌زمینه روشن/تیره\n- صفحه داخلی/طراحی\n\n**خروجی‌ها:** `LogoPreviewPage`"
  },
  {
    "id": "file-src-app-auth-login-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/auth/login/page.tsx",
    "keywords": [
      "page",
      "src/app/auth/login/page.tsx",
      "login page.tsx"
    ],
    "body": "**هدف:** ورود با credentials.\n\n- signIn next-auth redirect false\n- callbackUrl از query\n- reset success banner\n\n**خروجی‌ها:** `LoginPage`, `LoginForm`"
  },
  {
    "id": "file-src-app-auth-register-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/auth/register/page.tsx",
    "keywords": [
      "page",
      "src/app/auth/register/page.tsx",
      "register page.tsx"
    ],
    "body": "**هدف:** ثبت‌نام کاربر جدید.\n\n- POST `/api/register`\n- redirect به login\n\n**خروجی‌ها:** `RegisterPage`"
  },
  {
    "id": "file-src-app-auth-forgot-password-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/auth/forgot-password/page.tsx",
    "keywords": [
      "page",
      "src/app/auth/forgot-password/page.tsx",
      "forgot-password page.tsx"
    ],
    "body": "**هدف:** درخواست لینک بازیابی رمز.\n\n- POST `/api/auth/forgot-password`\n- نمایش devResetUrl در dev\n\n**خروجی‌ها:** `ForgotPasswordPage`"
  },
  {
    "id": "file-src-app-auth-reset-password-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/auth/reset-password/page.tsx",
    "keywords": [
      "page",
      "src/app/auth/reset-password/page.tsx",
      "reset-password page.tsx"
    ],
    "body": "**هدف:** تنظیم رمز جدید با token.\n\n- token از query param\n- POST `/api/auth/reset-password`\n- invalid token UI\n\n**خروجی‌ها:** `ResetPasswordPage`, `ResetPasswordForm`"
  },
  {
    "id": "file-src-app-content-id-read-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/content/[id]/read/page.tsx",
    "keywords": [
      "page",
      "src/app/content/[id]/read/page.tsx",
      "read page.tsx"
    ],
    "body": "**هدف:** صفحه مطالعه PDF.\n\n- force-dynamic\n- increment downloadCount\n- PdfViewer + reviews + SaveButton\n\n**خروجی‌ها:** `ReadPage`"
  },
  {
    "id": "file-src-app-content-id-listen-page-tsx",
    "category": "pages",
    "title": "page",
    "filePath": "src/app/content/[id]/listen/page.tsx",
    "keywords": [
      "page",
      "src/app/content/[id]/listen/page.tsx",
      "listen page.tsx"
    ],
    "body": "**هدف:** صفحه پخش پادکست/صوتی.\n\n- مشابه read با AudioPlayer\n- فقط AUDIOBOOK\n\n**خروجی‌ها:** `ListenPage`"
  },
  {
    "id": "file-prisma-seed-ts",
    "category": "database",
    "title": "seed",
    "filePath": "prisma/seed.ts",
    "keywords": [
      "seed",
      "prisma/seed.ts",
      "prisma seed.ts"
    ],
    "body": "**هدف:** seed اولیه دیتابیس برای توسعه.\n\n- ۶ category، admin/user/authors\n- ۱۰ کتاب نمونه (PDF local + archive)\n- reviews نمونه\n- credentials: admin@marketplace.local / admin123\n\n**خروجی‌ها:** script `main()` (CLI)\n\n**استفاده‌شده در:** `npm run db:seed` (package.json)"
  },
  {
    "id": "file-prisma-import-archive-ts",
    "category": "database",
    "title": "import-archive",
    "filePath": "prisma/import-archive.ts",
    "keywords": [
      "import-archive",
      "prisma/import-archive.ts",
      "prisma import-archive.ts"
    ],
    "body": "**هدف:** CLI واردات کتاب از Internet Archive.\n\n- فراخوانی `runArchiveImport`\n- bypass proxy سیستم\n\n**خروجی‌ها:** script CLI\n\n**استفاده‌شده در:** npm script import"
  },
  {
    "id": "file-prisma-data-verified-archive-ts",
    "category": "database",
    "title": "verified-archive",
    "filePath": "prisma/data/verified-archive.ts",
    "keywords": [
      "verified-archive",
      "prisma/data/verified-archive.ts",
      "data verified-archive.ts"
    ],
    "body": "**هدف:** کاتالوگ شناسه‌های تأییدشده archive.org.\n\n- آرایه `VERIFIED_ARCHIVE` با identifier, title, creator, type, categorySlug\n- کار آفلاین بدون API\n\n**خروجی‌ها:** `VERIFIED_ARCHIVE`, `VerifiedArchiveItem`\n\n**استفاده‌شده در:** `archive-import.ts`"
  },
  {
    "id": "file-prisma-data-archive-catalog-ts",
    "category": "database",
    "title": "archive-catalog",
    "filePath": "prisma/data/archive-catalog.ts",
    "keywords": [
      "archive-catalog",
      "prisma/data/archive-catalog.ts",
      "data archive-catalog.ts"
    ],
    "body": "**هدف:** کاتalog گسترده‌تر archive (fallback).\n\n- `ARCHIVE_CATALOG` با metadata اضافی pdf/audio\n- merge در buildMergedCatalog\n\n**خروجی‌ها:** `ARCHIVE_CATALOG`, `ArchiveCatalogItem`\n\n**استفاده‌شده در:** `archive-import.ts`"
  },
  {
    "id": "file-c-Users-ASUS-Projects-ebook-marketplace-capacitor-config-ts",
    "category": "config",
    "title": "capacitor.config",
    "filePath": "c:/Users/ASUS/Projects/ebook-marketplace/capacitor.config.ts",
    "keywords": [
      "capacitor.config",
      "c:/Users/ASUS/Projects/ebook-marketplace/capacitor.config.ts",
      "ebook-marketplace capacitor.config.ts"
    ],
    "body": "**هدف:** پیکربندی اپ موبایل Capacitor.\n\n- appId: ir.khaneketab.app\n- server URL به production (remote web app)\n- SplashScreen و StatusBar plugins\n\n**خروجی‌ها:** default CapacitorConfig"
  },
  {
    "id": "file-c-Users-ASUS-Projects-ebook-marketplace-vercel-json",
    "category": "config",
    "title": "vercel.json",
    "filePath": "c:/Users/ASUS/Projects/ebook-marketplace/vercel.json",
    "keywords": [
      "vercel.json",
      "c:/Users/ASUS/Projects/ebook-marketplace/vercel.json",
      "ebook-marketplace vercel.json"
    ],
    "body": "**هدف:** تنظیمات deploy Vercel.\n\n- buildCommand: prisma generate + next build --webpack\n- framework nextjs\n- region fra1 (فرانکfurt)\n\n**خروجی‌ها:** JSON config"
  },
  {
    "id": "backend-139",
    "category": "backend",
    "title": "content.ts — منطق محتوا",
    "filePath": "src/lib/content.ts",
    "keywords": [
      "content",
      "query"
    ],
    "body": "getApprovedContents, getContentById, getRecommendations, mapContent. queries Prisma + averageRating"
  },
  {
    "id": "backend-140",
    "category": "backend",
    "title": "notifications.ts — ایجاد اعلان",
    "filePath": "src/lib/notifications.ts",
    "keywords": [
      "notification"
    ],
    "body": "createNotification on approve/reject. types CONTENT_*, REVIEW_*, TICKET_REPLY"
  },
  {
    "id": "backend-141",
    "category": "backend",
    "title": "email.ts — SMTP",
    "filePath": "src/lib/email.ts",
    "keywords": [
      "email",
      "smtp"
    ],
    "body": "sendPasswordResetEmail — nodemailer. env SMTP_*"
  }
] as DocEntry[];

export const DOC_COUNT = 142;
